// curl "https://api.coincap.io/v2/assets"
// curl "https://api.coincap.io/v2/assets/bitcoin"
export declare namespace Assets {

    export interface Asset {
        id?: string;
        rank?: string;
        symbol?: string;
        name?: string;
        supply?: string;
        maxSupply?: string;
        marketCapUsd?: string;
        volumeUsd24Hr?: string;
        priceUsd?: string;
        changePercent24Hr?: string;
        vwap24Hr?: string;
        explorer?: string;
    }

    export interface RootObject {
        data: Asset[];
        timestamp: number;
    }

}


// curl "https://api.coincap.io/v2/assets/bitcoin/history?interval=d1"
export declare namespace History {

    export interface Datum {
        priceUsd: string;
        time: number;
        date: Date;
    }

    export interface RootObject {
        data: Datum[];
        timestamp: number;
    }

}


// curl "https://api.coincap.io/v2/assets/bitcoin/markets"
export declare namespace Markets {

    export interface Datum {
        exchangeId: string;
        baseId: string;
        quoteId: string;
        baseSymbol: string;
        quoteSymbol: string;
        volumeUsd24Hr: string;
        priceUsd: string;
        volumePercent: string;
    }

    export interface RootObject {
        data: Datum[];
        timestamp: number;
    }

}


// Final type for assets after JSON parsing
export declare namespace FinalAssets {

    export interface History {
        priceUsd: string;
        time: any;
        date: Date;
    }

    export interface Asset {
        id: string;
        rank: string;
        symbol: string;
        name: string;
        supply: string;
        maxSupply: string;
        marketCapUsd: string;
        volumeUsd24Hr: string;
        priceUsd: string;
        changePercent24Hr: string;
        vwap24Hr: string;
        explorer: string;
        history: History[];
    }

    export interface RootObject {
        data: Asset[];
        timestamp: number;
    }

}




// Generated by https://quicktype.io

/*export interface TopLevel {
    error:     string;
    data:      { [key: string]: null | string }[];
    timestamp: number;
}*/


// Generated by https://quicktype.io

/*export interface TopLevel {
    data:      Datum[];
    timestamp: number;
}

export interface Datum {
    id:                string;
    rank:              string;
    symbol:            string;
    name:              string;
    supply:            string;
    maxSupply:         null | string;
    marketCapUsd:      string;
    volumeUsd24Hr:     string;
    priceUsd:          string;
    changePercent24Hr: string;
    vwap24Hr:          string;
    explorer:          string;
    history:           History[];
}

export interface History {
    priceUsd: string;
    time:     number;
    date:     string;
}*/



// Generated by https://quicktype.io

/*
export interface TopLevel {
    data:      Datum[];
    timestamp: number;
}

export interface Datum {
    bitcoin?:  Bitcoin;
    ethereum?: Bitcoin;
}

export interface Bitcoin {
    asset:   { [key: string]: null | string };
    history: History[];
}

export interface History {
    priceUsd: string;
    time:     number;
    date:     string;
}
*/

/*declare module namespace {

    export interface Asset {
        id: string;
        rank: string;
        symbol: string;
        name: string;
        supply: string;
        maxSupply: string;
        marketCapUsd: string;
        volumeUsd24Hr: string;
        priceUsd: string;
        changePercent24Hr: string;
        vwap24Hr: string;
        explorer: string;
    }

    export interface History {
        priceUsd: string;
        time: any;
        date: Date;
    }

    export interface Bitcoin {
        asset: Asset;
        history: History[];
    }

    export interface Asset2 {
        id: string;
        rank: string;
        symbol: string;
        name: string;
        supply: string;
        maxSupply?: any;
        marketCapUsd: string;
        volumeUsd24Hr: string;
        priceUsd: string;
        changePercent24Hr: string;
        vwap24Hr: string;
        explorer: string;
    }

    export interface History2 {
        priceUsd: string;
        time: any;
        date: Date;
    }

    export interface Ethereum {
        asset: Asset2;
        history: History2[];
    }

    export interface Datum {
        bitcoin: Bitcoin;
        ethereum: Ethereum;
    }

    export interface RootObject {
        data: Datum[];
        timestamp: number;
    }

}*/