// Generated by https://quicktype.io

export interface TopLevel {
    data:      { [key: string]: null | string }[];
    timestamp: number;
}

declare module Assets {

    export interface Datum {
        id: string;
        rank: string;
        symbol: string;
        name: string;
        supply: string;
        maxSupply: string;
        marketCapUsd: string;
        volumeUsd24Hr: string;
        priceUsd: string;
        changePercent24Hr: string;
        vwap24Hr: string;
        explorer: string;
    }

    export interface RootObject {
        data: Datum[];
        timestamp: number;
    }

}
